modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "${mod_licence}"

[[mods]]
modId = "yuushya_modelling"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "pack.png"
displayURL = "${mod_homepage}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''
    ${mod_description}
    '''
#logoFile = ""

[[dependencies.yuushya_modelling]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya_modelling]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya_modelling]]
modId = "architectury"
type = "required"
versionRange = "[12.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.yuushya_modelling]]
modId = "yuushya"
type = "optional"
versionRange = "[2.0.0,)"
ordering = "AFTER"
side = "BOTH"