modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "yuushya_modelling"
version = "2.3.0"
displayName = "Yuushya Modelling"
logoFile = "../pack.png"
displayURL = "https://yuushya.com/townscape/"
credits = "Solid support from the team and the community!"
authors = "Coco, Xiao2 or XiLaiTL, SQwatermark, XieZai, Hikari, LD_Anvil, Little Panda, Crystal1921"
description = '''
    Added several tools to move, rotate or resize blocks like doing 3D modelling
    '''

[[mixins]]
config="yuushya_modelling.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.yuushya_modelling]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya_modelling]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
