modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "${mod_licence}"

[[mods]]
modId = "yuushya_modelling"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "pack.png"
displayURL = "${mod_homepage}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''
    ${mod_description}
    '''
#logoFile = ""

[[dependencies.yuushya_modelling]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya_modelling]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya_modelling]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.yuushya_modelling]]
modId = "yuushya"
mandatory = false
versionRange = "[2.0.0,)"
ordering = "AFTER"
side = "BOTH"